# Redis 配置文件
# https://raw.githubusercontent.com/redis/redis/7.0/redis.conf

bind 0.0.0.0
protected-mode no
port 6379

tcp-backlog 511
timeout 0
tcp-keepalive 300

daemonize no
loglevel notice

databases 16
always-show-logo no
set-proc-title yes
proc-title-template "{title} {listen-addr} {server-mode}"

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
rdb-del-sync-files no
dir /data

# 密码等生产配置，如果为空则免密 (为本地测试方便，不设置requirepass)
# requirepass 123456
